[main]
title = "Сочетания клавиш VIM"
column_count = 3

[[categories]]
name = "Курсор"
bindings = [
    { keys = "h", desc = "передвинуть курсор влево" },
    { keys = "j", desc = "передвинуть курсор на одну фактическую строку вниз" },
    { keys = "k", desc = "передвинуть курсор на одну фактическую строку вверх" },
    { keys = "l", desc = "передвинуть курсор вправо" },
    { keys = ["g", "j"], desc = "передвинуть курсор на одну видимую строку вниз" },
    { keys = ["g", "k"], desc = "передвинуть курсор на одну видимую строку вверх" },
]

[[categories]]
name = "Перемещение по строке"
bindings = [
    { keys = "w", desc = "вперед на начало слова" },
    { keys = "e", desc = "вперед на конец слова" },
    { keys = "b", desc = "назад на начало слова" },
    { keys = ["g", "e"], desc = "назад по конец слова" },
    { keys = "0", desc = "на начало строки" },
    { keys = "^", desc = "на первый непустой символ строки" },
    { keys = ["g", "_"], desc = "на последний непустой символ в строке" },
    { keys = "$", desc = "на конец строки" },
]

[[categories]]
name = "Перемещение по документу"
bindings = [
    { keys = "H", desc = "переместиться к началу экрана" },
    { keys = "M", desc = "переместиться к середине экрана" },
    { keys = "L", desc = "переместиться к концу экрана" },
    { keys = "%", desc = "переместиться к парному символу (), {}, []" },
    { keys = ["g", "g"], desc = "переместиться на первую строку" },
    { keys = "G", desc = "переместиться на последнюю строку" },
    { keys = ["5", "G"], desc = "переместиться на 5 строку" },
    { keys = "}", desc = "переместиться к следующему параграфу" },
    { keys = "{", desc = "переместиться к предыдущему параграфу" },
    { keys = ["z", "z"], desc = "сдвинуть буфер так, чтобы курсор оказался в центре" },
    { keys = ["ctrl", "b"], desc = "переместиться назад на целый экран" },
    { keys = ["ctrl", "f"], desc = "переместитья вперед на целый экран" },
    { keys = ["ctrl", "d"], desc = "переместиться вперед на половину экрана" },
    { keys = ["ctrl", "u"], desc = "переместиться назад на половину экрана" },
]

[[categories]]
name = "Режим вставки"
bindings = [
    { keys = "i", desc = "вставка перед курсором" },
    { keys = "I", desc = "вставка в начало строки" },
    { keys = "a", desc = "вставка после курсора" },
    { keys = "A", desc = "вставка в конец строки" },
    { keys = "o", desc = "добавление новой строки под текущей" },
    { keys = "O", desc = "добавление новой строки над текущей" },
    { keys = ["e", "a"], desc = "вставка после конца слова" },
    { keys = "esc", desc = "выход из режима вставки" },
]

[[categories]]
name = "Режим выделения"
bindings = [
    { keys = "v", desc = "перейти в режим выделения символов" },
    { keys = "V", desc = "перейти в режим выделения строк" },
    { keys = ["ctrl", "alt", "v"], desc = "режим выделения прямоугольного блока" },
    { keys = "o", desc = "переместить курсор в блоке выделения влево" },
    { keys = "O", desc = "переместить курсор в блоке выделения вправо" },
    { keys = ["g", "v"], desc = "выделить текст, выделенный в прошлый раз" },
    { keys = "I", desc = "вставка симовлов в блочном выделении (после esc вставляет символы в каждую строку)" },
    { keys = "c", desc = "аналогично I, но удаляет содержимое блока" },
    { keys = "C", desc = "аналогично I, но удаляет символы от левого края блока до конца строки" },
    { keys = "u", desc = "изменить регистр на нижний" },
    { keys = "U", desc = "изменить регистр на верхний" },
    { keys = "~", desc = "переключить регистр" },
    { keys = "J", desc = "объединить строки в области выделения" },
    { keys = ["r", "x"], desc = "заменить символы в области выделения на x" },
    { keys = "<", desc = "сдвинуть блок влево" },
    { keys = ">", desc = "сдвинуть блок вправо" },
]

[[categories]]
name = "Редактирование"
bindings = [
    { keys = "r", desc = "заменить один символ" },
    { keys = ["c", "c"], desc = "заменить всю строку" },
    { keys = ["c", "w"], desc = "заменить всё слово" },
    { keys = ["c", "$"], desc = "заменить до конца строки" },
    { keys = "s", desc = "удалить символ и перейти в режим вставки" },
    { keys = "u", desc = "отменить" },
    { keys = ["ctrl", "r"], desc = "вернуть" },
    { keys = ".", desc = "повторить последнюю команду" },
]

[[categories]]
name = "Перемещение к символу"
bindings = [
    { keys = ["f", "x"], desc = "перем. к след. символу x в строке" },
    { keys = ["t", "x"], desc = "установить курсор за след. символом x в строке" },
    { keys = ["F", "x"], desc = "переместиться к пред. символу x в строке" },
    { keys = ["T", "x"], desc = "установить курсор за пред. символом x в строке" },
    { keys = ";", desc = "повторить предыдущее f, t, F или T перемещение" },
    { keys = ",", desc = "повторить предыдущее f, t, F или T перемещение в обратном направлении" },
]

[[categories]]
name = "Поиск"
bindings = [
    { keys = "/", desc = "режим поиска" },
    { keys = "?", desc = "поиск в обратном направлении" },
    { keys = "n", desc = "повторить поиск вперед" },
    { keys = "N", desc = "повторить поиск назад" },
    { keys = "*", desc = "поиск слова под курсором" },
    { keys = "#", desc = "поиск слова под курсором в обратном направлении" },
]

[[categories]]
name = "Замена"
bindings = [
    { keys = ":%s/исх_текст/замена/g", desc = "заменить все вхождения исходного текста" },
    { keys = ":.s/исх_текст/замена/g", desc = "заменить все вхождения исходного текста в текущей строке" },
]
